### ISSUE TITLE
如何在assistant功能模块中，获得stream流式的响应

### ISSUE THREAD

**Issue by TtonyLiang** [liyf1/chatgpt-plus#9]
你好，感谢你的project，看了以后很受启发。
我正在做类似的工作。现在遇到了一个问题：  如何在assistant功能模块中，获得stream流式的响应？

如果您有解决方向的话，请告诉我，谢谢！

**Comment by liyf1** [comment]
https://platform.openai.com/docs/api-reference/assistants-streaming
你好，官方目前是支持流式的
<img width="922" alt="image" src="https://github.com/liyf1/chatgpt-plus/assets/49024327/020421f9-e3e0-4af6-874e-d36b17b243f2">

**Comment by TtonyLiang** [comment]
嗯嗯，这个我有在官网看到。 现在有个问题：如何获取想要的响应结果？ 是直接获得creatRun的接口的响应？ 还是像原来一样先轮询 调用retrieveRun，再从message中取？
